//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC5_Realtime_Chat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public string number { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
